package bolen.frame.model;

public class UpmsUser {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column upms_user.user_id
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column upms_user.username
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column upms_user.password
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column upms_user.salt
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	private String salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column upms_user.realname
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column upms_user.avatar
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	private String avatar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column upms_user.phone
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column upms_user.email
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column upms_user.sex
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	private Byte sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column upms_user.locked
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	private Byte locked;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column upms_user.ctime
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	private Long ctime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column upms_user.user_id
	 * @return  the value of upms_user.user_id
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column upms_user.user_id
	 * @param userId  the value for upms_user.user_id
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column upms_user.username
	 * @return  the value of upms_user.username
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column upms_user.username
	 * @param username  the value for upms_user.username
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column upms_user.password
	 * @return  the value of upms_user.password
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column upms_user.password
	 * @param password  the value for upms_user.password
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column upms_user.salt
	 * @return  the value of upms_user.salt
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column upms_user.salt
	 * @param salt  the value for upms_user.salt
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column upms_user.realname
	 * @return  the value of upms_user.realname
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column upms_user.realname
	 * @param realname  the value for upms_user.realname
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column upms_user.avatar
	 * @return  the value of upms_user.avatar
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column upms_user.avatar
	 * @param avatar  the value for upms_user.avatar
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column upms_user.phone
	 * @return  the value of upms_user.phone
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column upms_user.phone
	 * @param phone  the value for upms_user.phone
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column upms_user.email
	 * @return  the value of upms_user.email
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column upms_user.email
	 * @param email  the value for upms_user.email
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column upms_user.sex
	 * @return  the value of upms_user.sex
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public Byte getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column upms_user.sex
	 * @param sex  the value for upms_user.sex
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public void setSex(Byte sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column upms_user.locked
	 * @return  the value of upms_user.locked
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public Byte getLocked() {
		return locked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column upms_user.locked
	 * @param locked  the value for upms_user.locked
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public void setLocked(Byte locked) {
		this.locked = locked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column upms_user.ctime
	 * @return  the value of upms_user.ctime
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public Long getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column upms_user.ctime
	 * @param ctime  the value for upms_user.ctime
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	public void setCtime(Long ctime) {
		this.ctime = ctime;
	}

	@Override
	public String toString() {
		return "UpmsUser [userId=" + userId + ", username=" + username + ", password=" + password + ", salt=" + salt
				+ ", realname=" + realname + ", avatar=" + avatar + ", phone=" + phone + ", email=" + email + ", sex="
				+ sex + ", locked=" + locked + ", ctime=" + ctime + "]";
	}
    
    
}