package bolen.frame.mapper;

import bolen.frame.model.UpmsUser;

public interface UpmsUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upms_user
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upms_user
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	int insert(UpmsUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upms_user
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	int insertSelective(UpmsUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upms_user
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	UpmsUser selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upms_user
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	int updateByPrimaryKeySelective(UpmsUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upms_user
	 * @mbggenerated  Fri Mar 30 17:13:22 CST 2018
	 */
	int updateByPrimaryKey(UpmsUser record);
}